# Generated by Django 6.1.1 on 2026-09-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='members.member'),
        ),
    ]
