# Generated by Django 6.1.1 on 2026-09-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
